### ISSUE TITLE
Clarification on adding custom token validator

### ISSUE THREAD

**Issue by tomstreeter** [sprocketbox/laravel-jwt#10]
I have reason to add another criteria to the validation of an already issued token (with no need to mess with creating custom claims: the standard ones are fine). The check I want to add is to make sure the the token was issued *after* the last time the user's record was updated. The idea is that any existing tokens could be invalidated merely by changing the password on the backend (or any other field, as it turns out). The app I'm building really shouldn't be used on public machines, but I assume all users will be as likely to do something stupid as I am (and that's pretty likely).  It's a safety feature. (Setting the TTL to 12 or 24 hours would realistically accomplish the same thing, but this is bugging me).

I've managed to implement this as middleware that runs on every hit to an api route, but I have a nagging feeling I've duplicated a whole lot of functionality for no good reason (unless my ignorance is considered a good reason.  I don't, for the record)

(Figuring out how to find the cookie and extract the token *was* a fun puzzle, to be honest). 

Reading through the both the README and the JwtGuard code has me convinced that that code snippet about adding custom validator* logic would allow me to check that the IAT claim is newer than the last time the user record was updated, but still run the validation that's run out of the box  All without the overhead of using middleware to do it. 

The only problem is that I'm really not sure WHERE I'd use that code you provided as an example.  Do I put it in a service provider?  Do I need to put in the controllers that will need the check accomplished? In middleware? I seriously doubt I'm going to surprise you by saying that my experience with Laravel is limited. I'm not interested in taking up a ton of your time, so pointers to relevant documentation would be welcome.  A little more context for how to do custom validation would be welcome to whatever extent you're able to provide it.

As always, many thanks for this package.

----------------------

*(note:  in your README.md table of contents you call it "customer validation" which may or may not be what you meant.)

**Comment by tomstreeter** [comment]
There seems to be something about my learning process that involves me making a complete fool of myself publicly. I've gotten used to it, but I'm not fond of wasting other people's time with the process.

The answer to my question, of course, is that one place I can put the custom validation logic is in the boot() method of `App\Providers\AuthServiceProvider.php` like so:

```
    public function boot()
    {
        $this->registerPolicies();
        //
        Auth::guard('api')->setTokenValidator(function (\Lcobucci\JWT\Token $token, \Sprocketbox\JWT\JWTGuard $guard) {
            $tokenIsCurrent= false;
            $userId  = $token->getClaim('sub');
            $iat = new Carbon($token->getClaim('iat'));
            $userUpdatedAt = User::find($userId)->updated_at;
            $issuedAfterUpdated = $iat->greaterThanOrEqualTo($userUpdatedAt);
            if ($issuedAfterUpdated) {
                $tokenIsCurrent= true;
            }
            return $tokenIsCurrent;
        });
    }
```


If there's a better way to get to `$user->updated_at` I'd welcome the pointer, but essentially this is doing what I want it to do.

I think I can quit bothering you now. Many thanks for your patience.

**Comment by ollieread** [comment]
@tomstreeter Sorry that it took me so long to get back to you about this.

I'm not sure the validation that's currently there works for what you want, and it does create a somewhat redundant database call as the user is then loaded again upon successful validation.

Another thing to mention is that the token validation is replaced by the custom validation, so you'd need to copy in the default code. The term 'validation' can be confusing because of how Laravel uses it but it's essentially making sure that the token is valid for this service, ie, hasn't expired, audience matches and the signature is correct. I would imagine that your use case would come _AFTER_ the authentication, where you could check if the user has been updated and invalidate the token.

This package doesn't _currently_ have a mechanism for invalidating tokens before their expiry date, but it is something I'm looking into.

Thanks for the note about 'customer validation', at the time of writing I was doing a lot of work on a project that seemed to involve customer something every 10 lines.

**Comment by tomstreeter** [comment]
You're right about that extra db call. Luckily it bothered me too and I kept poking at it. The process of figuring out why there was no way around it finally flipped a switch for me about how guards work in Laravel, which then cascaded into how a bunch of other things fit together.  You're absolutely right that my check is something that needs to come after the standard check (and only under very specific conditions).  Turns out I can do what I need with the check living in a controller method.

So the whole thing was kind of a rabbit hole, but a very instructive one. Really instructive.  Well worth the time.

**Comment by ollieread** [comment]
@tomstreeter I'm glad you solved this. I would recommend going down to the middleware route mind you, that way it's attached to whatever request you want, and you can add it to groups.

The way Laravels auth works is actually quite confusing. It's a topic I've been meaning to write about considering the confusion that surrounds it.
