### ISSUE TITLE
callback in $auth->extend() does not run

### ISSUE THREAD

**Issue by devfake** [sprocketbox/laravel-jwt#3]
Possibly that I did something wrong. But I worked through the readme and implemented everything. Changed the `api` guard in `config/auth.php` and passed the second parameter into `attempt()`. 

But no cookies are set if i log in.

I use the `api.php` route file, and therefore the middlewares for cookies are missing in the 'api' middlewareGroup in `Http/Kernel.php`. If i'm adding these middlewares for cookies, it worked. 

Is that correct? Is there something missing in the documentation? Or is there something wrong with my setup?

**Comment by devfake** [comment]
Ok, had conflicts with another jwt package x)

**Comment by ollieread** [comment]
@devfake I believe I need to update the documentation to say that, but yes you do need that middleware.

**Comment by tomstreeter** [comment]
If I'm understanding correctly:
```
\App\Http\Middleware\EncryptCookies::class,
\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
\Illuminate\Session\Middleware\StartSession::class,
```
needs to be added to the 'api' middlware group in Kernel.php?

It *would* explain why the JWT gets written to the cookie, because I sure couldn't figure out why it would otherwise. (My hypothesis involved animal sacrifice and and it made my cats nervous).

**Comment by ollieread** [comment]
@tomstreeter You only need the `Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class` middleware though I'd recommend using the `EncryptCookies` one too. I'll update the README to reflect this.

**Comment by tomstreeter** [comment]
Thanks; both for the reply and writing the package in the first place.
